apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: "2022-04-11T19:49:36Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "7461"
  uid: 503199bc-3e00-4a7d-94c5-e12b3d2d66bd
data:
  accounts.ripleymj: logi,apiKey
  accounts.uuguser1: login,apiKey
  accounts.uuguser2: login,apiKey
  accounts.uuguser3: login,apiKey
  accounts.uuguser4: login,apiKey
  accounts.uuguser5: login,apiKey
  accounts.uuguser6: login,apiKey
  accounts.uuguser7: login,apiKey
  accounts.uuguser8: login,apiKey
  accounts.uuguser9: login,apiKey
  accounts.uuguser10: login,apiKey
  accounts.uuguser11: login,apiKey
  accounts.uuguser12: login,apiKey
  accounts.uuguser13: login,apiKey
  accounts.uuguser14: login,apiKey
  accounts.uuguser15: login,apiKey
  accounts.uuguser16: login,apiKey
  accounts.uuguser17: login,apiKey
  accounts.uuguser18: login,apiKey
  accounts.uuguser19: login,apiKey
  accounts.uuguser20: login,apiKey
  accounts.uuguser21: login,apiKey
  accounts.uuguser22: login,apiKey
  accounts.uuguser23: login,apiKey
  accounts.uuguser24: login,apiKey
  accounts.uuguser25: login,apiKey
  accounts.uuguser26: login,apiKey
  accounts.uuguser27: login,apiKey
  accounts.uuguser28: login,apiKey
  accounts.uuguser29: login,apiKey
  accounts.uuguser30: login,apiKey
